services:
  signal-api:
    image: "bbernhard/signal-cli-rest-api"
    volumes:
      - .local/share/signal-api:/home/.local/share/signal-cli
    ports:
      - "8080:8080"
    environment:
      MODE: "json-rpc"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"